name: "Playwright Tests"

env:
  BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  pull_request:
    branches: [main, development]

jobs:
  preview-deployment:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install -g pnpm
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN
      - name: Deploy Project Artifacts to Vercel
        run: |
          deployment_url="$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)"
          deployment_hostname=${deployment_url#*://}
          deployment_url_ref=$(echo "$deployment_url" | awk -F'-' '{print $3}')
          # intended_alias_hostname=$(echo "${{ vars.BASE_DOMAIN }}" | sed 's~^[a-zA-Z]*://~~') # remove https
          intended_alias_hostname="${deployment_url_ref}${BASE_DOMAIN}"

          deployment_id=$(curl -s -G \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v6/deployments/$deployment_hostname" | jq -r '.id')

          echo "Deployment ID: $deployment_id"
          echo "Deployment URL: $deployment_hostname"
          echo "Deployment URL Ref: $deployment_url_ref"
          echo "Intended Alias: $intended_alias_hostname"

          if [ -z "$deployment_id" ]; then
            echo "Failed to retrieve deployment ID. Exiting..."
            exit 1
          fi

          current_alias_hostname=$(curl -s -G \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v4/aliases/$intended_alias_hostname?projectId=$VERCEL_PROJECT_ID&teamId=$VERCEL_ORG_ID" | jq -r '.alias')

          echo "Current Alias: $current_alias_hostname"

          if [[ "$current_alias_hostname" == "$intended_alias_hostname" ]]; then
            # This would ensure that an error does not occur while deleting a non-existent alias
            vercel alias rm $intended_alias_hostname --token=$VERCEL_TOKEN --yes
          fi


          ALIAS_RESPONSE=$(curl --location --globoff \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v2/deployments/$deployment_id/aliases?teamId=$VERCEL_ORG_ID" \
            --header "Content-Type: application/json" \
            --data "{\"alias\": \"$intended_alias_hostname\"}")

          echo "Alias Response: $ALIAS_RESPONSE"

          # Verify Alias is Set
          if echo "$ALIAS_RESPONSE" | grep -q '"error"'; then
            echo "Failed to set alias. Response: $ALIAS_RESPONSE"
            exit 1
          fi

          echo "Alias set successfully for deployment: $deployment_id"

          preview_url="https://${intended_alias_hostname}"
          # echo "Extended Preview URL: $preview_url"

          #Save URL to artifact
          echo "Extended Preview URL: $preview_url"
          echo "$preview_url" > preview_url.txt
      - uses: actions/upload-artifact@v4
        with:
          name: preview-url
          path: preview_url.txt
          retention-days: 1

  playwright-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: preview-deployment
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: preview-url
      - name: Load URL
        run: echo "PREVIEW_URL=$(cat preview_url.txt)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run test #Wait for deployment to complete and run Playwright tests
        env:
          NODE_ENV: preview
        run: |
          npx wait-on $PREVIEW_URL && PREVIEW_URL=$PREVIEW_URL npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  post-playwright-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: playwright-tests
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: preview-url
      - name: Load URL
        run: echo "PREVIEW_URL=$(cat preview_url.txt)" >> $GITHUB_ENV
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Delete Vercel Domain Alias
        run: |
          echo "Alias to be deleted is $PREVIEW_URL"
          vercel alias rm $PREVIEW_URL --token=$VERCEL_TOKEN --yes
